# Generated by Django 4.2.7 on 2023-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido_paterno", models.CharField(max_length=50)),
                ("apellido_materno", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "asignaturas_tomadas",
                    models.ManyToManyField(to="course_management.asignatura"),
                ),
            ],
        ),
    ]
